/**
 * Copyright (C) 2010-2019 EMBL-European Bioinformatics Institute (EMBL-EBI),
 * Deutsches Krebsforschungszentrum (DKFZ)
 *
 * This file is part of Jummp.
 *
 * Jummp is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * Jummp is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with Jummp; if not, see <http://www.gnu.org/licenses/agpl-3.0.html>.
 */

package net.biomodels.jummp.deployment.biomodels

import grails.transaction.Transactional
import org.springframework.beans.factory.InitializingBean

/**
 * Abstract class to be used to handle services concerning auto generated models
 *
 * @author: Tung Nguyen <tnguyen@ebi.ac.uk>
 */
@Transactional
abstract class AutoGenModelService implements InitializingBean {
    @Override
    void afterPropertiesSet() throws Exception {
        log.info("Finished the bean initialisation")
    }

    Map getRepresentatives(List<String> missingIds) {
        List list = findRepresentatives(missingIds)
        Map representatives = [:]
        list.each {
            representatives.put(it[0], it[1])
        }
        representatives
    }

    abstract String getRepresentativeId(String id)

    abstract List<String> findMissing()

    abstract List findRepresentatives(List<String> missing)

    String getCategoryForModel(String id) {
        AutoGeneratedCategory.createCriteria().get {
            projections {
                property 'categoryName'
            }
            eq "modelIdentifier", id
        }
    }

    Map getModelCategoryMap(String pattern) {
        List entries = AutoGeneratedCategory.all.findAll {
            it.modelIdentifier.startsWith(pattern)
        }

        Map<String, Set<AutoGeneratedCategory>> returned =
            new TreeMap<String, TreeSet>(abcOrderCategoryNameComparator())
        entries.each {
            TreeSet<AutoGeneratedCategory> categories
            String firstLetter = it.categoryName.toString().substring(0, 1)
            if (returned.containsKey(firstLetter)) {
                categories = returned.get(firstLetter)
                categories.add(it)
            } else {
                categories = new TreeSet<AutoGeneratedCategory>(abcOrderCategoryComparator())
                categories.add(it)
                returned.put(firstLetter, categories)
            }
        }
        returned
    }

    static final class AlphabeticalOrderCategory implements Comparator<AutoGeneratedCategory> {
        @Override
        int compare(AutoGeneratedCategory cate1, AutoGeneratedCategory cate2) {
            cate1.categoryName <=> cate2.categoryName
        }
    }

    static AlphabeticalOrderCategory abcOrderCategoryComparator() {
        new AlphabeticalOrderCategory()
    }

    static final class AlphabeticalOrderCategoryName implements Comparator<String> {
        @Override
        int compare(String cate1, String cate2) {
            cate1 <=> cate2
        }
    }

    static AlphabeticalOrderCategoryName abcOrderCategoryNameComparator() {
        new AlphabeticalOrderCategoryName()
    }
}
