/**
 * Copyright (C) 2010-2019 EMBL-European Bioinformatics Institute (EMBL-EBI),
 * Deutsches Krebsforschungszentrum (DKFZ)
 *
 * This file is part of Jummp.
 *
 * Jummp is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * Jummp is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with Jummp; if not, see <http://www.gnu.org/licenses/agpl-3.0.html>.
 **/

package net.biomodels.jummp.deployment.biomodels

import grails.transaction.Transactional

/**
 * This service provides means of operating and managing the map between representative and missing models in
 * Path2Models.
 *
 * @author Tung Nguyen <tnguyen@ebi.ac.uk>
 */
@Transactional
class P2mService {
    List<String> findMissing() {
        // executeQuery() queries are not supported in unit tests with Grails 2.5, use criteria queries instead
        P2MMapping.createCriteria().list {
            projections {
                property 'member'
            }
        }
    }

    String getRepresentativeId(String id) {
        P2MMapping map = P2MMapping.findByMember(id)
        if (map) {
            return map.representative
        } else {
            // the identifier in question is the model itself
            map = P2MMapping.findByRepresentative(id)
            return map?.representative ?: null
        }
    }

    Map getRepresentatives(List<String> missingIds) {
        Map representatives = [:]
        missingIds.each { String modelId ->
            String rep = getRepresentativeId(modelId)
            representatives.put(modelId, rep)
        }
        representatives
    }

    String getCategoryForModel(String id) {
        AutoGeneratedCategory.createCriteria().get {
            projections {
                property 'categoryName'
            }
            eq "modelIdentifier", id
        }
    }

    Map getModelCategoryMap() {
        List entries = AutoGeneratedCategory.all.findAll {
            it.modelIdentifier.startsWith("BMID")
        }

        Map<String, Set<AutoGeneratedCategory>> returned =
            new TreeMap<String, TreeSet>(P2mService.AbcOrderCategoryNameComparator())
        entries.each {
            TreeSet<AutoGeneratedCategory> categories
            String firstLetter = it.categoryName.toString().substring(0, 1)
            if (returned.containsKey(firstLetter)) {
                categories = returned.get(firstLetter)
                categories.add(it)
            } else {
                categories = new TreeSet<AutoGeneratedCategory>(P2mService.AbcOrderCategoryComparator())
                categories.add(it)
                returned.put(firstLetter, categories)
            }
        }
        returned
    }

    static final class AlphabeticalOrderCategory implements Comparator<AutoGeneratedCategory> {
        @Override
        int compare(AutoGeneratedCategory cate1, AutoGeneratedCategory cate2) {
            cate1.categoryName <=> cate2.categoryName
        }
    }

    static AlphabeticalOrderCategory AbcOrderCategoryComparator() {
        new AlphabeticalOrderCategory()
    }

    static final class AlphabeticalOrderCategoryName implements Comparator<String> {
        @Override
        int compare(String cate1, String cate2) {
            cate1 <=> cate2
        }
    }

    static AlphabeticalOrderCategoryName AbcOrderCategoryNameComparator() {
        new AlphabeticalOrderCategoryName()
    }
}
