package net.biomodels.jummp.deployment.biomodels

import grails.test.mixin.TestFor
import spock.lang.Specification

/**
 * See the API for {@link grails.test.mixin.domain.DomainClassUnitTestMixin} for usage instructions
 * @testers     Tung Nguyen <nvntung@gmail.com>
 * @date        2019.07.09
 */
@TestFor(AutoGeneratedCategory)
class AutoGeneratedCategorySpec extends Specification {
    String modelIdentifier
    String categoryName

    def setup() {
        modelIdentifier = "BMID000000140669"
        categoryName = "Acaryochloris"
    }

    void "test the table has nothing at the initial statge"() {
        expect: "there is no record in the table"
        !AutoGeneratedCategory.count
    }

    void "test the saving operation of data into the table"() {
        when: "creating and saving a sample in the table"
        def cate = AutoGeneratedCategory.findOrSaveByModelIdentifierAndCategoryName(modelIdentifier, categoryName)
        cate.save(flush: true)

        then: "we can retrieve the latest saved record"
        AutoGeneratedCategory.count == 1
        AutoGeneratedCategory.findByModelIdentifier(modelIdentifier).modelIdentifier == modelIdentifier
        AutoGeneratedCategory.findByCategoryName(categoryName).categoryName == categoryName
    }
}
