/*
 * Copyright (C) 2010-2018 EMBL-European Bioinformatics Institute (EMBL-EBI),
 * Deutsches Krebsforschungszentrum (DKFZ)
 *
 * This file is part of Jummp.
 *
 * Jummp is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * Jummp is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with Jummp; if not, see <http://www.gnu.org/licenses/agpl-3.0.html>.
 */

import grails.plugin.springsecurity.acl.AclSid
import groovy.sql.Sql
import groovyx.gpars.GParsPool
import java.time.Duration
import java.time.Instant
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.*
import net.biomodels.jummp.annotationstore.*
import net.biomodels.jummp.core.model.ModelFormatTransportCommand
import net.biomodels.jummp.core.model.ModelState
import net.biomodels.jummp.core.model.ModelTransportCommand
import net.biomodels.jummp.core.model.RepositoryFileTransportCommand
import net.biomodels.jummp.core.model.RevisionTransportCommand
import net.biomodels.jummp.core.model.ValidationState
import net.biomodels.jummp.core.model.identifier.ModelIdentifierUtils
import net.biomodels.jummp.core.model.identifier.decorator.AbstractAppendingDecorator
import net.biomodels.jummp.core.model.identifier.decorator.FixedLiteralAppendingDecorator
import net.biomodels.jummp.core.model.identifier.decorator.VariableDigitAppendingDecorator
import net.biomodels.jummp.core.model.identifier.generator.DefaultModelIdentifierGenerator
import net.biomodels.jummp.model.*
import net.biomodels.jummp.plugins.security.Person
import net.biomodels.jummp.plugins.security.Role
import net.biomodels.jummp.plugins.security.User
import net.biomodels.jummp.plugins.security.UserRole
import org.springframework.security.acls.domain.BasePermission
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
import org.springframework.security.core.context.SecurityContextHolder

String modelFolder = System.getenv("MODEL_FOLDER")

/**
 * Simple holder for variables defined in this script that are accessed by different methods.
 */
class Ctx {
    static final Role roleUser = Role.findByAuthority("ROLE_USER")
    static final String submitterName      = "Path2Models project"
    static final String submitterAccount   = "path2models@googlegroups.com"
    static final String passwordString     = "*autogenerated*"
    // cannot access springSecurityService from non-static ApplicationContext in a static context
    static final String encrypted          = "ee2d7c43d5273361d429b20423031fc4ce6d81bfb759d79ee2750956000a74ca"
    static final def processedCount        = new AtomicInteger()
    static final def failureCount          = new AtomicInteger()
    static final String adminUsername      = System.getenv("ADMIN_USER")
    static final String adminPass          = System.getenv("ADMIN_PWD")
    static def bioModelsConnection = Sql.newInstance(System.getenv("DB_URL"),
            System.getenv("DB_USER"), System.getenv("DB_PWD"), "com.mysql.jdbc.Driver"
    )
    static final Person submitterPerson    = Person.findOrSaveByUserRealName(submitterName)
    static final User submitter            = account
    // there are two possible manuscripts that can be associated with these models
    // PMID for Path2Models models
    static final String P2M_PAPER_ID       = "24180668"
    // PMID for the models from the Nature Pathway Interaction Database (PID)
    static final String PID_PAPER_ID       = "22923304"
    // the filesystem_path value in the auto_gen_models table for PID models
    static final String MARKER_FOR_PID_MODELS = "non-metabolic/nci"
    static Publication p2mPaper
    static Publication pidPaper
    // auth token for admin account; used by worker threads to publish models
    static def adminAuth

    /**
     * Very simple means of executing an action as a different user than the one
     * that is currently authenticated.
     *
     * Performs the action defined by closure as the user defined by Authentication
     * object auth, then reverts to the original authentication.
     *
     * Suitable for lightweight work for which we need not create a separate thread.
     */
    static def simpleRunAs = { auth, closure ->
        def currentAuth
        try {
            currentAuth = SecurityContextHolder.context.authentication
            SecurityContextHolder.context.authentication = auth
            def result = closure.call()
            return result
        } finally {
            if (currentAuth) {
                SecurityContextHolder.context.authentication = currentAuth
            } else {
                SecurityContextHolder.clearContext()
            }
        }
    }

    private static User getAccount() {
        def newUser = User.findOrSaveWhere(username: submitterAccount, person: submitterPerson,
                email: submitterAccount, password: encrypted, accountLocked: false,
                accountExpired: false, passwordExpired: false, enabled: true
        )
        // create AclSid and add UserRole
        AclSid.findOrSaveWhere(sid: submitterAccount, principal: true)
        UserRole.findOrSaveWhere(user: newUser, role: roleUser)
        newUser
    }

}

/*
 * Model-centric log holder.
 *
 * Printing to System.out in a multi-threaded environment introduces unnecessary blocking and also
 * makes the order in which the statements are printed unpredictable.
 *
 * This class addresses both issues: all log messages pertaining to a particular model are queued, so
 * the order is preserved. Also, because we process each model in a dedicated thread, there's no need
 * to block.
 * See also the printModelLog() method.
 */
class ModelLogger {
    /**
     * Log for model-related messages.
     *
     * Keys represent model identifiers. Values represent pairs of ordered sets of messages
     * corresponding to the error log and the info log respectively.
     *
     * Since all messages relating to a model will be inserted by the same thread, there is no
     * need to use locks.
     */
    static def messageLog = new ConcurrentHashMap<String, ModelLogger>()
    /**
     * The error log for this model
     */
    Set err
    /**
     * The message log for this model
     */
    Set out

    void logMsg(def msg) {
        out << msg
    }

    void errMsg(def msg) {
        err << msg
    }

    String toString() {
        "out: $out, err: $err"
    }
}

void addModelMsg(String model, def msg) {
    def logger = getOrCreateModelLogger model
    logger.logMsg msg
}

void addModelError(String model, def msg) {
    Ctx.failureCount.incrementAndGet()
    def logger = getOrCreateModelLogger model
    logger.errMsg msg
}

ModelLogger getOrCreateModelLogger(String model) {
    ModelLogger.messageLog.putIfAbsent(model,
            new ModelLogger(err: new LinkedHashSet(), out: new LinkedHashSet()))
    ModelLogger.messageLog[model]
}

/**
 * Uploads the model, adds the information from the old system and publishes it.
 */
void handleModelFolder(File modelFolder) {
    Ctx.processedCount.incrementAndGet()
    String id = modelFolder.name
    // set up a transaction
    def persistenceInterceptor = ctx.persistenceInterceptor
    try {
        persistenceInterceptor?.init()
        if (Model.findBySubmissionId(id)) {
            addModelMsg(id, "The model is already imported, skipping...")
            return
        }
        def revisionCmd = createRevisionCmdForModelFolder(id, modelFolder)
        if (!revisionCmd) { // something went wrong, the error has already been logged
            return
        }

        def model = ctx.modelService.uploadValidatedModel(revisionCmd.files, revisionCmd)
        if (!model || model?.hasErrors()) {
            addModelError(id, "Model upload failed: ${model?.errors?.allErrors}")
            return
        } else {
            model.submissionId = id
            if (model.save()) {
                portDataFromLegacySystem(model)
                publish(model.revisions[0])
            } else {
                def err = model.errors.allErrors
                addModelError(id, "Could not update the submission identifier: $err")
                // TODO set tx as rollback only, we may need to avoid flushing!
            }
        }
    } finally {
        persistenceInterceptor?.flush()
        persistenceInterceptor?.destroy()
    }
}

RepositoryFileTransportCommand createRepoFile(File file, boolean isMainFile, String description) {
    new RepositoryFileTransportCommand(path: file.absolutePath, mainFile: isMainFile,
             userSubmitted: true, hidden: false, description: description)
}

RevisionTransportCommand createRevisionCmdForModelFolder(String id, File folder) {
    File modelFile = null
    List<File> additionals = []
    for (File child: folder.listFiles()) {
        if (child.name.endsWith('.xml')) {
            modelFile = child
        } else {
            additionals << child
        }
    }

    if (!modelFile) {
        addModelError(id, "Missing model file in folder '${folder.name}'")
        return null
    }

    def mainFileRFTC = createRepoFile(modelFile, true, 'Path2Models entry for E. coli')
    def otherRepoFiles = additionals.collect { f ->
        createRepoFile f, false, 'All files for E. coli'
    }
    def modelFileFormatService = ctx.modelFileFormatService
    ModelFormatTransportCommand fmtCmd = modelFileFormatService.inferModelFormat([mainFileRFTC])
    def fmt = ModelFormat.findByIdentifierAndFormatVersion(fmtCmd.identifier, fmtCmd.formatVersion)
    def errors = []
    boolean isValid  = modelFileFormatService.validate([modelFile], fmt.identifier, errors)
    if (!isValid) {
        addModelError(id, "Model failed validation: $errors")
        return null
    }

    String modelName = modelFileFormatService.extractName([modelFile], fmt)
    String modelDesc = modelFileFormatService.extractDescription([modelFile], fmt)

    def repoFileCommands = [mainFileRFTC] + otherRepoFiles
    def modelCmd = new ModelTransportCommand(submitter: Ctx.submitterAccount, format: fmtCmd,
            submissionDate: new Date())

    new RevisionTransportCommand(files: repoFileCommands, format: fmtCmd, validated: isValid,
            name: modelName, description: modelDesc, validationLevel: ValidationState.APPROVED,
            comment: "Import of '$modelName'.", model: modelCmd)
}

void  printModelLog() {
    ModelLogger.messageLog.keySet().sort().each { modelId ->
        def logger = ModelLogger.messageLog[modelId]
        def infoMessages = logger.out
        infoMessages.each { m -> println("$modelId: $m") }
    }
    if (Ctx.failureCount.get()) {
        System.err.println("Failed to import the following models:")
        ModelLogger.messageLog.keySet().sort().each { modelId ->
            def logger = ModelLogger.messageLog[modelId]
            def errorMessages = logger.err
            errorMessages.each { m -> System.err.println("$modelId: $m") }
        }
    }
}

/**
 * Creates and returns an authentication token for the given username and password.
 * Note that the owner of the credentials is *not* authenticated until the token is
 * put in the SecurityContext (see simpleRunAs()).
 * Also note that, by default, SecurityContexts are thread-local.
 */
def getAuthTokenFor(String u, String p) {
    def token = new UsernamePasswordAuthenticationToken(u, p)
    ctx.authenticationManager.authenticate(token)
}

/**
 * Ensures that the pointers to the Path2Models and PID manuscripts are initialised.
 * Throws an assertion failure if there are any problems.
 */
void fetchPublicationDetails() {
    Ctx.p2mPaper = findOrRetrievePubMedPaper(Ctx.P2M_PAPER_ID)
    Ctx.pidPaper = findOrRetrievePubMedPaper(Ctx.PID_PAPER_ID)
    assert Ctx.p2mPaper && Ctx.pidPaper
}

/**
 * Returns a persisted Publication object for the given PMID.
 * Fetches the publication details from Europe PMC if the manuscript is not already in the db.
 */
Publication findOrRetrievePubMedPaper(String id) {
    def paper = Publication.findByLink id
    if (!paper) {
        println "Retrieving publication $id from EuropePMC..."
        def publicationCmd = ctx.pubMedService.fetchPublicationData(id)
        paper = ctx.publicationService.fromCommandObject publicationCmd
    }
    paper
}

/**
 * Updates the clerical details about a submission (e.g. publication date) so
 * that they match the information from the old system.
 */
void portDataFromLegacySystem(Model m) {
    assert m?.revisions?.size() > 0
    def revision = m.revisions[0]
    def info = Ctx.bioModelsConnection.firstRow("""\
select submission_date, publication_date, original_model, filesystem_path
from auto_gen_models where id = ?
""", m.submissionId)

    // dates
    revision.uploadDate = info["submission_date"]
    m.firstPublished = info["publication_date"]

    // publication
    String fsPath = info["filesystem_path"]
    if (fsPath?.startsWith(Ctx.MARKER_FOR_PID_MODELS)) {
        m.publication = Ctx.pidPaper
    } else {
        m.publication = Ctx.p2mPaper
    }
    if (!m.save()) {
        throw new IllegalStateException("Failed to add data from old system: ${m.errors.allErrors}")
    }

    // annotations
    String originalModel = info["original_model"]
    String author        = revision.owner.person.userRealName

    // original model
    if (originalModel) {
        createBMAnnotation(revision, author, "source", "http://biomodels.net/model-qualifiers/",
                "http://purl.org/dc/elements/1.1/", originalModel)
    }
}

/**
 * Convenience method for adding a model-level annotation to a revision.
 */
RevisionAnnotation createBMAnnotation(Revision r, String creator, String qualifierAccession,
        String qualifierType, String qualifierNS, String xrefUri, String dataType = "unknown") {
    Qualifier predicate = Qualifier.findOrSaveWhere(qualifierType: qualifierType, namespace:
        qualifierNS, uri: "${qualifierNS}${qualifierAccession}", accession: qualifierAccession)

    ResourceReference xref = ResourceReference.findOrSaveWhere(uri: xrefUri, datatype: dataType)
    if (!xref || xref.hasErrors()) {
        addModelError r.model.submissionId, xref.errors.allError
        return null
    }
    def statement = Statement.findOrCreateWhere(subjectId: 'modelLevelAnnotation',
            qualifier: predicate, object: xref)
    def modelElementType = ModelElementType.findByModelFormatAndName(r.format, 'model')
    def elementAnnotation
    // can only use findOrCreate with associations if the associated object is already saved
    if (statement.id) {
        elementAnnotation = ElementAnnotation.findOrCreateByCreatorIdAndStatementAndModelElementType(
                creator, statement, modelElementType)
    } else {
        elementAnnotation = new ElementAnnotation(modelElementType: modelElementType,
                creatorId: creator, statement: statement)
    }
    // need to flush in order to obtain an ID
    if (!elementAnnotation.save(flush: true) || elementAnnotation.hasErrors()) {
        throw new IllegalStateException("""Failed to create model level annotation \
${qualifierNS}${qualifierAccession} $xrefUri for revision ${r.id}: \
${elementAnnotation.errors.allErrors}
""")
    }
    RevisionAnnotation.create(r, elementAnnotation)
}

/**
 * Makes a given revision readable to anyone.
 */
void publish(Revision r) {
    Ctx.simpleRunAs(Ctx.adminAuth, {
        def aclUtilService = ctx.aclUtilService
        aclUtilService.addPermission(r, "ROLE_USER", BasePermission.READ)
        aclUtilService.addPermission(r, "ROLE_ANONYMOUS", BasePermission.READ)
        r.state = ModelState.PUBLISHED
        if (!r.save()) {
            def err = r.errors.allErrors
            throw new IllegalStateException("Cannot publish revision ${r.id}: $err")
        }
    })
}

// set the application context reference in POGOs that expect it
RevisionTransportCommand.context = ctx

// don't let Camel shut itself down within 5 minutes of the importer finishing.
// wait for all models to be indexed instead.
def camelContext = ctx.camelContext
camelContext.shutdownStrategy.setTimeout(Long.MAX_VALUE)

// ensure we have reference publications persisted into the database
fetchPublicationDetails()

def duration
def startTime = Instant.now()
try {
    def modelFolderPattern = ~/BMID\d{12}/
    final int POOL_SIZE    = Math.min(25, 2 * Runtime.getRuntime().availableProcessors())
    println("Pool size is $POOL_SIZE, model folder is $modelFolder")

    def submitterAuth = getAuthTokenFor(Ctx.submitterAccount, Ctx.passwordString)
    Ctx.adminAuth     = getAuthTokenFor(Ctx.adminUsername, Ctx.adminPass)

    GParsPool.withPool(POOL_SIZE) {
        GParsPool.runForkJoin(new File(modelFolder)) { File root ->
            final String rootName = root.name
            if (rootName ==~ modelFolderPattern) {
                Ctx.simpleRunAs(submitterAuth, {
                    try {
                        handleModelFolder root
                    } catch (IllegalStateException ise) {
                        addModelError(rootName, ise.message)
                    }  catch (Exception e) {
                        addModelError(rootName, "oops: $e")
                        //e.printStackTrace()
                    }
                })
            } else { // fork dedicated task for each sub-folder
                def subFolders = root.listFiles(new FileFilter() {
                    boolean accept(File candidate) {
                        candidate.isDirectory()
                    }
                })
                subFolders.each { File child ->
                    forkOffChild child
                }
            }
        }
    }

    // wait for pending indexing jobs to complete before stopping
    def indexRequestDispatcher = ctx.camelContext.routes.find {
        // we use seda:exec to invoke the indexer
        it.consumer.endpoint.endpointKey.startsWith("seda://exec")
    }.consumer

    int pendingIndexingJobs = indexRequestDispatcher.pendingExchangesSize
    while (pendingIndexingJobs > 0) {
        println("Waiting for ${pendingIndexingJobs} models to be indexed...")
        Thread.sleep(30000)
        pendingIndexingJobs = indexRequestDispatcher.pendingExchangesSize
    }
} catch (Exception e) {
    System.err.println("Generic exception encountered while importing the models: $e")
} finally {
    Ctx.bioModelsConnection?.close()
    duration = Duration.between(startTime, Instant.now())
    String formattedDuration = duration.toString()
    println("Imported ${Ctx.processedCount.get()} models (${Ctx.failureCount.get()} failures) in $formattedDuration")
    printModelLog()
}

