/*
 * Copyright (C) 2010-2019 EMBL-European Bioinformatics Institute (EMBL-EBI),
 * Deutsches Krebsforschungszentrum (DKFZ)
 *
 * This file is part of Jummp.
 *
 * Jummp is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * Jummp is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with Jummp; if not, see <http://www.gnu.org/licenses/agpl-3.0.html>.
 */


import grails.plugin.springsecurity.SpringSecurityUtils
import grails.plugin.springsecurity.acl.AclUtilService
import groovyx.gpars.GParsPool
import net.biomodels.jummp.core.ModelException
import net.biomodels.jummp.core.ModelService
import net.biomodels.jummp.core.adapters.ModelAdapter
import net.biomodels.jummp.core.adapters.RevisionAdapter
import net.biomodels.jummp.core.model.*
import net.biomodels.jummp.deployment.biomodels.AutoGeneratedCategory
import net.biomodels.jummp.deployment.biomodels.UhlenModelMapping
import net.biomodels.jummp.model.Model
import net.biomodels.jummp.model.ModelFormat
import net.biomodels.jummp.model.ModellingApproach
import net.biomodels.jummp.model.RepositoryFile
import net.biomodels.jummp.model.Revision
import net.biomodels.jummp.plugins.git.GitSupport
import net.biomodels.jummp.plugins.security.User
import net.biomodels.jummp.plugins.security.UserRole
import org.eclipse.jgit.api.Git
import org.eclipse.jgit.api.errors.GitAPIException
import org.eclipse.jgit.lib.ObjectId
import org.eclipse.jgit.lib.Repository
import org.springframework.orm.hibernate4.SessionHolder
import org.springframework.security.acls.domain.BasePermission
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
import org.springframework.security.core.Authentication
import org.springframework.security.core.GrantedAuthority
import org.springframework.security.core.context.SecurityContextHolder
import org.springframework.transaction.TransactionDefinition
import org.springframework.transaction.TransactionStatus
import org.springframework.transaction.support.TransactionSynchronizationManager

import java.nio.file.Paths
import java.time.Duration
import java.time.Instant
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger


/*
 * Script to update the Uhlen2017 models by grouping them into 21 categories based on their cancer type.
 *
 * The script expects a folder containing files of the new version for each representative model. It creates
 * a new revision with these new files, sets the modelling approach to metabolic network (MAMO_0000040),
 * archives the non-representative models and publishes the latest revision for the representative model.
 *
 * In case of errors, we roll back the newly created revision, perform a git revert and append the
 * message to the model's error log. INFO and ERROR messages about each model are printed after the script
 * completes.
 *
 * @author Mihai Glonț mihai.glont@ebi.ac.uk
 * @date   20191206
 */

String modelFolder = System.getenv("MODEL_FOLDER")

/**
 * Simple holder for variables defined in this script that are accessed by different methods.
 */
class Ctx {
    static final String MODEL_ID_LIKE_QUERY_PATTERN = "MODEL170711%"
    static final def processedCount = new AtomicInteger()
    static final def failureCount = new AtomicInteger()

    static final User submitter = getSubmitterAccount()
    static final Authentication submitterAuth = createTokenForUser(submitter)
    static final String adminUsername = System.getenv("ADMIN_USER")
    // auth token for admin account; used by worker threads to publish models
    static final Authentication adminAuth = createTokenForUser(adminUsername)
    // the current session
    static final SessionHolder session = null
    static final String metabolicNetwork = "http://identifiers.org/mamo/MAMO_0000040"

    /**
     * Very simple means of executing an action as a different user than the one
     * that is currently authenticated.
     *
     * Performs the action defined by closure as the user defined by Authentication
     * object auth, then reverts to the original authentication.
     *
     * Suitable for lightweight work for which we need not create a separate thread.
     */
    static def simpleRunAs = { auth, closure ->
        def currentAuth
        try {
            currentAuth = SecurityContextHolder.context.authentication
            SecurityContextHolder.context.authentication = auth
            def result = closure.call()
            return result
        } finally {
            if (currentAuth) {
                SecurityContextHolder.context.authentication = currentAuth
            } else {
                SecurityContextHolder.clearContext()
            }
        }
    }

    /*
     * Returns the User account owning the models to be updated.
     *
     * All models were submitted by the same account, and we guard this assumption with a runtime (fatal) exception.
     *
     * @return the User account that should be used to update these models.
     */
    private static User getSubmitterAccount() {
        // we deliberately call get() because we expect a single result; getting >1 results would be an error which
        // would be propagated upstream to the callees of this method.
        User owner = Revision.createCriteria().get {
            projections {
                distinct "owner"
            }
            model {
                like "submissionId", MODEL_ID_LIKE_QUERY_PATTERN
            }
        }

        owner
    }


    /*
     * Creates and returns an authentication token for the given user.
     * Note that the owner of the credentials is *not* authenticated until the token is put in the SecurityContext
     * (see simpleRunAs()). Also note that, by default, SecurityContexts are thread-local.
     *
     * @param username the username for the account whose credentials should be used to create the authentication token
     * @return the authentication token which, if placed in the security context of the current thread, would allow us
     *      to log in as the given user.
     */
    private static UsernamePasswordAuthenticationToken createTokenForUser(User u) {
        assert u
        def authorities = UserRole.findAllByUser(u)*.role*.authority.join(",")
        List<GrantedAuthority> roles = SpringSecurityUtils.parseAuthoritiesString authorities
        return new UsernamePasswordAuthenticationToken(u.username, u.password, roles)
    }

    /*
     * Creates and returns an authentication token for the given user.
     *
     * @param username the username for the account whose credentials should be used to create the authentication token
     * @return an authentication token for the given user
     * @see {@link Ctx#createTokenForUser(net.biomodels.jummp.plugins.security.User)}
     */
    private static UsernamePasswordAuthenticationToken createTokenForUser(String username) {
        assert username : "Username required but not defined"
        createTokenForUser(User.findByUsername(username))
    }
}

/*
 * Model-centric log holder.
 *
 * Printing to System.out in a multi-threaded environment introduces unnecessary blocking and also
 * makes the order in which the statements are printed unpredictable.
 *
 * This class addresses both issues: all log messages pertaining to a particular model are queued, so
 * the order is preserved. Also, because we process each model in a dedicated thread, there's no need
 * to block.
 * See also the printModelLog() method.
 */
class ModelLogger {
    /**
     * Log for model-related messages.
     *
     * Keys represent model identifiers. Values represent pairs of ordered sets of messages
     * corresponding to the error log and the info log respectively.
     *
     * Since all messages relating to a model will be inserted by the same thread, there is no
     * need to use locks.
     */
    static def messageLog = new ConcurrentHashMap<String, ModelLogger>()
    /**
     * The error log for this model
     */
    Set err
    /**
     * The message log for this model
     */
    Set out

    void logMsg(def msg) {
        out << msg
    }

    void errMsg(def msg) {
        err << msg
    }

    String toString() {
        "out: $out, err: $err"
    }
}

static void addModelMsg(String model, def msg) {
    def logger = getOrCreateModelLogger model
    logger.logMsg msg
}

static void addModelError(String model, def msg) {
    Ctx.failureCount.incrementAndGet()
    def logger = getOrCreateModelLogger model
    logger.errMsg msg
}

static ModelLogger getOrCreateModelLogger(String model) {
    ModelLogger.messageLog.putIfAbsent(model,
            new ModelLogger(err: new LinkedHashSet(), out: new LinkedHashSet()))
    ModelLogger.messageLog[model]
}

static SessionHolder getCurrentSession() {
    TransactionSynchronizationManager.getResource(ctx.sessionFactory) as SessionHolder
}

static boolean markSessionAsRollbackOnly(SessionHolder session) {
    assert session : "Hibernate Session not available. Was persistenceInterceptor.init() called?"
    session.setRollbackOnly()
    session.isRollbackOnly()
}

/**
 * Returns the file system location where a given model's files are stored.
 *
 * @param model the model for which to look up the corresponding working directory subfolder.
 * @return a {@link File} denoting the model folder
 */
static File findModelDotGitDirectory(Model model) {
    assert model?.vcsIdentifier : "Model instance having a vcsIdentifier expected"
    assert grailsApp : "Missing grailsApplication bean reference 'grailsApp'. Are you using grails run-script ?"
    def base = grailsApp.config.jummp.vcs.workingDirectory
    assert base instanceof String
    Paths.get(base, model.vcsIdentifier, ".git").toFile()
}

/*
 * Handles the mechanics of reverting a model revision from the Git repo.
 *
 * You should probably call {@link revertGitRevision(Revision) instead.
 * @param repository the initialised repository reference for that revision's model.
 * @param revision the revision whose file system changes we should revert
 * @throws GitAPIException if there was an internal error which prevented us from reverting the revision
 * @see {@link revertGitRevision()}
 */
static void doRevertGitRevision(Repository repository, Revision revision) throws GitAPIException {
    def revisionId = Objects.requireNonNull(revision, "Revision to revert required").vcsId
    ObjectId toRevert = Objects.requireNonNull(repository, "Model folder Git repo required").resolve(revisionId)
    Git git = new Git(repository)
    def newHead = git.revert()
        .include(toRevert)
        .call()

    def msg = "Reverted ${revisionId}. HEAD is now ${newHead.name}"
    addModelMsg(revision.model.submissionId, msg)
}

/**
 * Convenience method for reverting a revision in a Git repository.
 *
 * @param revision the revision whose file changes should be reverted.
 * @throws GitAPIException if JGit encountered an error while performing the revert command.
 */
static void revertGitRevision(Revision revision) throws GitAPIException {
    assert revision
    def model = revision.model
    File baseDir = findModelDotGitDirectory(model)

    Repository repository = GitSupport.buildRepository(baseDir)
    try {
        doRevertGitRevision(repository, revision)
    } finally {
        repository.close()
    }
}

/**
 * Atomically deletes a revision, its repository files and associated ACL permissions.
 *
 * <p>Since {@link net.biomodels.jummp.core.ModelService#addValidatedRevision(java.util.List, java.util.List, net.biomodels.jummp.core.model.RevisionTransportCommand)}
 * inserts the new revision in a dedicated transaction which gets committed and flushed before the method returns, we
 * cannot use transaction rollback to undo that insertion &ndash; we need to use another dedicated transaction which
 * undoes that work.</p>
 * <p>We also run <tt>git revert</tt> so that the
 *
 * <p>This method will throw an {@code IllegalStateException} if any of the entities could not be deleted.</p>
 * @param toDelete the revision that should be deleted
 * @see rollBackSessionAndRevision()
 */
static void undoRevisionInsertion(Revision toDelete) {
    assert toDelete
    AclUtilService aclUtilService = ctx.aclUtilService as AclUtilService
    // a revision and its ACLs are inserted in a dedicated transaction, so we cannot simply
    def txSettings = [propagationBehavior: TransactionDefinition.PROPAGATION_NESTED,
                      isolationLevel: TransactionDefinition.ISOLATION_READ_COMMITTED]
    Revision.withTransaction(txSettings) { TransactionStatus status ->
        try {
            aclUtilService.deleteAcl(toDelete)
            String query = "delete RepositoryFile rf where rf.revision = :revision"

            RepositoryFile.executeUpdate(query, [revision: toDelete])
            toDelete.delete(flush: true)
            revertGitRevision(toDelete)
        } catch (Exception e) {
            // rollback everything in this transaction and notify the callee
            status.setRollbackOnly()
            def msg = "Could not delete Revision ${toDelete.id}: ${e.message}"
            throw new IllegalStateException(msg)
        }
    }
}

/**
 * Marks the current Hibernate session as rollback only and atomically deletes all entities associated with a revision.
 *
 * <p>To be used as the preferred rollback mechanism in code invoked after the new model revision has been created and
 * persisted into the database via {@code modelService.addValidatedRevision()}, assuming the insertion has been successful.</p>
 *
 * @param revision the revision which should be deleted
 * @see undoRevisionInsertion()
 * @see markSessionAsRollbackOnly()
 */
static void rollBackSessionAndRevision(Revision revision, SessionHolder session) {
    markSessionAsRollbackOnly(session)
    undoRevisionInsertion(revision)
}

/**
 * Convenience method for performing operations within a Hibernate Session.
 * @param callback a closure defining the work to be done
 * @param submissionFolder the model folder on which to operate
 * @return the result of the work performed, possibly null.
 */
static Object processModelInSession(Closure callback, File submissionFolder) {
    // set up a Hibernate session
    def persistenceInterceptor = ctx.persistenceInterceptor
    def session = null
    try {
        persistenceInterceptor?.init()
        session = getCurrentSession()
        callback.call(session, submissionFolder)
    } finally {
        if (!session?.rollbackOnly) {
            persistenceInterceptor?.flush()
        }
        persistenceInterceptor?.destroy()
    }
}

static Revision doInsertNewRevision(String modelId, File modelFolder, Model model) {
    Map<String, Object> revisionData = createRevisionCmdForModelFolder(modelId, modelFolder, model)
    if (!revisionData) { // something went wrong, the error has already been logged
        return null
    }
    RevisionTransportCommand revisionCmd               = revisionData.revision as RevisionTransportCommand
    List<RepositoryFileTransportCommand> filesToAdd    = revisionData.toAdd as List<RepositoryFileTransportCommand>
    List<RepositoryFileTransportCommand> filesToDelete = revisionData.toDelete as List<RepositoryFileTransportCommand>
    Revision newRevision = null
    try {
        newRevision = ((ModelService)ctx.modelService).addValidatedRevision(filesToAdd, filesToDelete, revisionCmd)
    } catch (ModelException e) {
        assert markSessionAsRollbackOnly(getCurrentSession()) : "Adding revision ${revisionCmd.properties} failed but could not roll back"
        addModelError(modelId, "ModelException thrown when inserting the new revision: $e.message")
    }
    newRevision
}

static RepositoryFileTransportCommand createRepoFile(File file, boolean isMainFile, String description) {
    new RepositoryFileTransportCommand(path: file.absolutePath, mainFile: isMainFile,
             userSubmitted: true, hidden: false, description: description)
}

/*
 * Infers the category for a submission given its files.
 *
 * All 21 updated Uhlen models have a predefined category they fall under.
 */
static String lookupAutoGeneratedCategory(String modelId) {
    def category = AutoGeneratedCategory.findByModelIdentifier(modelId)
    assert category : "No category found for representative model $modelId"

    category.categoryName
}

static Map<String, Object> createRevisionCmdForModelFolder(String id, File folder, Model model) {
    def repoFileMap = createRepoFiles(folder)
    RepositoryFileTransportCommand modelFile = repoFileMap.main as RepositoryFileTransportCommand
    List<RepositoryFileTransportCommand> additionals = repoFileMap.additionals as List<RepositoryFileTransportCommand>

    def modelFileFormatService = ctx.modelFileFormatService
    ModelFormatTransportCommand fmtCmd = modelFileFormatService.inferModelFormat([modelFile])
    def fmt = ModelFormat.findByIdentifierAndFormatVersion(fmtCmd.identifier, fmtCmd.formatVersion)
    def errors = []
    boolean isValid  = modelFileFormatService.validate([modelFile], fmt.identifier, errors)
    if (!isValid) {
        addModelError(id, "Model failed validation: $errors")
        return null
    }

    String modelName = modelFileFormatService.extractName([modelFile], fmt)
    String modelDesc = modelFileFormatService.extractDescription([modelFile], fmt)

    def repoFileCommands = [modelFile] + additionals
    def modelCmd = new ModelAdapter(model: model).toCommandObject(false)
    def filesToDelete = getRepoFilesOfLastRevision(model)
    def revisionCmd = new RevisionTransportCommand(files: repoFileCommands, format: fmtCmd, validated: isValid,
            name: modelName, description: modelDesc, validationLevel: ValidationState.APPROVED,
            comment: "Import of '$modelName'.", model: modelCmd)

    [revision: revisionCmd, toAdd: repoFileCommands, toDelete: filesToDelete]
}

static Map<String, Object> createRepoFiles(File folder) {
    def partitionedFiles = partitionMainAndAdditionalFiles(folder)
    File modelFile = partitionedFiles.main as File
    List<File> additionals = partitionedFiles.additionals as List<File>
    final String modelId = folder.name
    assert modelFile : "No main file found in submission folder $modelId"

    String modelCategory = lookupAutoGeneratedCategory(modelId)
    def mainFileRFTC = createRepoFile(modelFile, true, "Patient derived genome scale metabolic model for $modelCategory")
    def otherRepoFiles = additionals.collect { f ->
        createRepoFile f, false, "All '$modelCategory' models"
    }

    [main: mainFileRFTC, additionals: otherRepoFiles]
}

static Map<String, Object> partitionMainAndAdditionalFiles(File folder) {
    File modelFile = null
    // the main file is the SBML (.xml extension)
    // additionals should only contain <category_name>.zip -- the OMEX with the missing models
    List<File> additionals = []
    for (File child : folder.listFiles()) {
        if (child.name.endsWith('.xml')) {
            modelFile = child
        } else {
            additionals << child
        }
    }
    [main: modelFile, additionals: additionals]
}

static List<RepositoryFileTransportCommand> getRepoFilesOfLastRevision(Model model) {
    Revision latest = model.revisions.max { it.revisionNumber }
    RevisionTransportCommand revisionCmd = new RevisionAdapter(revision: latest).toCommandObject()
    revisionCmd.files
}

void  printModelLog() {
    ModelLogger.messageLog.keySet().sort().each { modelId ->
        def logger = ModelLogger.messageLog[modelId]
        def infoMessages = logger.out
        infoMessages.each { m -> println("$modelId: $m") }
    }
    if (Ctx.failureCount.get()) {
        System.err.println("Failed to import the following models:")
        ModelLogger.messageLog.keySet().sort().each { modelId ->
            def logger = ModelLogger.messageLog[modelId]
            def errorMessages = logger.err
            errorMessages.each { m -> System.err.println("$modelId: $m") }
        }
    }
}

/**
 * Makes a given revision readable to anyone.
 */
static void publish(Revision r) {
    Ctx.simpleRunAs(Ctx.adminAuth, {
        def aclUtilService = ctx.aclUtilService
        aclUtilService.addPermission(r, "ROLE_USER", BasePermission.READ)
        aclUtilService.addPermission(r, "ROLE_ANONYMOUS", BasePermission.READ)
        r.state = ModelState.PUBLISHED
        if (!r.save()) {
            def err = r.errors.allErrors
            assert markSessionAsRollbackOnly(getCurrentSession()) : "Publishing $r failed ($err), but we could not roll back the session"
            throw new IllegalStateException("Cannot publish revision ${r.id}: $err")
        }
    })
}

static void assignModellingApproach(Model model) {
    def approach = ModellingApproach.findByResource(Ctx.metabolicNetwork)
    model.modellingApproach = approach
    addModelMsg(model.submissionId, "Set modelling approach to ${approach}")
}

/*
 * Support method for handleModelFolder()
 */
static void doHandleModelFolder(SessionHolder session, File submissionFolder) {
    assert submissionFolder?.isDirectory() : "'$submissionFolder' is not a model folder that exists"
    String id = submissionFolder.name
    Model m = Model.findBySubmissionId(id)
    assert m : "Model '$id' should have already been imported but isn't."

    Revision newRevision = doInsertNewRevision()

    if (!newRevision || newRevision?.hasErrors()) {
        addModelError(id, "Model update failed: ${newRevision?.errors?.allErrors}")
        assert markSessionAsRollbackOnly(session) : "No new revision could be inserted and we failed to roll back the current session"
    } else {
        assignModellingApproach(m)
        int deleteCount = markNonRepresentativeModelsAsDeleted(id)
        addModelMsg(id, "Archived $deleteCount non-representative models.")
        if (m.save()) {
            publish newRevision
        } else {
            def err = m.errors.allErrors
            addModelError(id, "Could not set the modelling approach: $err")
            rollBackSessionAndRevision newRevision, session
        }
    }
}

/**
 * Updates the model, adds the modelling approach, publishes its latest version and
 * deletes the non-representative models for the model's category.
 */
static void handleModelFolder(File modelFolder) {
    Ctx.processedCount.incrementAndGet()
    processModelInSession({ SessionHolder s, File folderToProcess ->
        doHandleModelFolder(s, folderToProcess)
    }, modelFolder)
}

/**
 * Archive non-representative models belonging to this category.
 *
 * <p>In order to avoid including non-representative models in the search results, we
 * need to mark them as deleted. The records are not actually removed, we simply set the
 * <tt>deleted</tt> column to <tt>true</tt> for the models in question.</p>
 *
 * <p>An assertion failure exception will be thrown if the model is not representative
 * for a Uhlen category or if the model does not exist in the database</p>
 * @param representativeId the submission id of a representative model for which we
 *          should delete the siblings.
 * @return the number of models that have been marked as deleted.
 */
static int markNonRepresentativeModelsAsDeleted(String representativeId) {
    assert UhlenModelMapping.findByRepresentative(representativeId) : "'$representativeId' is not representative for a Uhlen2017 category"
    assert Model.findBySubmissionId(representativeId) : "No model with identifier '$representativeId' submitted"

    String query = """\
update Model m set m.deleted = true where m.submissionId in (
    select umm.member from UhlenModelMapping umm where umm.representative = :representative)"""
    Model.executeUpdate(query, [representative: representativeId])
}

// set the application context reference in POGOs that expect it
RevisionTransportCommand.context = ctx

// don't let Camel shut itself down within 5 minutes of the importer finishing.
// wait for all models to be indexed instead.
def camelContext = ctx.camelContext
camelContext.shutdownStrategy.setTimeout(Long.MAX_VALUE)


def duration
def startTime = Instant.now()
try {
    def modelFolderPattern = ~/MODEL170711\d{4}/
    final int POOL_SIZE = Math.min(7, 2 * Runtime.getRuntime().availableProcessors())
    println("Pool size is $POOL_SIZE, model folder is $modelFolder")

    GParsPool.withPool(POOL_SIZE) {
        GParsPool.runForkJoin(new File(modelFolder)) { File root ->
            final String rootName = root.name
            if (rootName ==~ modelFolderPattern) {
                Ctx.simpleRunAs(Ctx.submitterAuth, {
                    try {
                        handleModelFolder root
                    } catch (IllegalStateException ise) {
                        addModelError(rootName, ise.message)
                    } catch (AssertionError e) {
                        addModelError rootName, e.toString()
                    }  catch (Exception e) {
                        addModelError(rootName, "oops: $e")
                        e.printStackTrace()
                    }
                })
            } else { // fork dedicated task for each sub-folder
                def subFolders = root.listFiles(new FileFilter() {
                    boolean accept(File candidate) {
                        candidate.isDirectory()
                    }
                })
                subFolders.each { File child ->
                    forkOffChild child
                }
            }
        }
    }

    // wait for pending indexing jobs to complete before stopping
    def indexRequestDispatcher = ctx.camelContext.routes.find {
        // we use seda:exec to invoke the indexer
        it.consumer.endpoint.endpointKey.startsWith("seda://exec")
    }.consumer

    int pendingIndexingJobs = indexRequestDispatcher.pendingExchangesSize
    while (pendingIndexingJobs > 0) {
        println("Waiting for ${pendingIndexingJobs} models to be indexed...")
        Thread.sleep(30000)
        pendingIndexingJobs = indexRequestDispatcher.pendingExchangesSize
    }
} catch (Exception e) {
    System.err.println("Generic exception encountered while importing the models: $e")
} finally {
    duration = Duration.between(startTime, Instant.now())
    String formattedDuration = duration.toString()
    println("Imported ${Ctx.processedCount.get()} models (${Ctx.failureCount.get()} failures) in $formattedDuration")
    printModelLog()
}
