/*
 * Copyright (C) 2010-2019 EMBL-European Bioinformatics Institute (EMBL-EBI),
 * Deutsches Krebsforschungszentrum (DKFZ)
 *
 * This file is part of Jummp.
 *
 * Jummp is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * Jummp is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with Jummp; if not, see <http://www.gnu.org/licenses/agpl-3.0.html>.
 */

import grails.plugin.springsecurity.SpringSecurityUtils
import grails.plugin.springsecurity.acl.AclUtilService
import groovy.transform.CompileDynamic
import groovy.transform.CompileStatic
import groovyx.gpars.GParsPool
import net.biomodels.jummp.core.JummpException
import net.biomodels.jummp.core.ModelException
import net.biomodels.jummp.core.ModelFileFormatService
import net.biomodels.jummp.core.ModelService
import net.biomodels.jummp.core.model.CurationState
import net.biomodels.jummp.core.model.ModelFormatTransportCommand
import net.biomodels.jummp.core.model.ModelTransportCommand
import net.biomodels.jummp.core.model.ModelState
import net.biomodels.jummp.core.model.RepositoryFileService
import net.biomodels.jummp.core.model.RepositoryFileTransportCommand
import net.biomodels.jummp.core.model.RevisionTransportCommand
import net.biomodels.jummp.core.model.ValidationState
import net.biomodels.jummp.deployment.biomodels.AutoGeneratedCategory
import net.biomodels.jummp.deployment.biomodels.UhlenModelMapping
import net.biomodels.jummp.model.Model
import net.biomodels.jummp.model.ModelFormat
import net.biomodels.jummp.model.ModellingApproach
import net.biomodels.jummp.model.RepositoryFile
import net.biomodels.jummp.model.Revision
import net.biomodels.jummp.plugins.git.GitSupport
import net.biomodels.jummp.plugins.security.User
import org.apache.camel.CamelContext
import org.apache.camel.component.seda.SedaConsumer
import org.codehaus.groovy.grails.commons.GrailsApplication
import org.codehaus.groovy.grails.support.PersistenceContextInterceptor
import org.eclipse.jgit.api.Git
import org.eclipse.jgit.api.errors.GitAPIException
import org.eclipse.jgit.lib.ObjectId
import org.eclipse.jgit.lib.Repository
import org.hibernate.SessionFactory
import org.springframework.context.ApplicationContext
import org.springframework.orm.hibernate4.SessionHolder
import org.springframework.security.acls.domain.BasePermission
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
import org.springframework.security.core.Authentication
import org.springframework.security.core.userdetails.UserDetails
import org.springframework.security.core.userdetails.UserDetailsService
import org.springframework.transaction.TransactionDefinition
import org.springframework.transaction.TransactionStatus
import org.springframework.transaction.support.TransactionSynchronizationManager

import java.nio.file.Paths
import java.time.Duration
import java.time.Instant
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger
import java.util.regex.Pattern


/*
 * Script to update the Uhlen2017 models by grouping them into 21 categories based on their cancer type.
 *
 * The script expects a folder containing files of the new version for each representative model. It creates
 * a new revision with these new files, sets the modelling approach to constraint-based (MAMO_0000009),
 * archives the non-representative models and publishes the latest revision for the representative model.
 *
 * In case of errors, we roll back the newly created revision, perform a git revert and append the
 * message to the model's error log. INFO and ERROR messages about each model are printed after the script
 * completes.
 *
 * @author Mihai Glonț mihai.glont@ebi.ac.uk
 * @date   20191206
 */

/**
 * Simple holder for variables defined in this script that are accessed by different methods.
 */
@CompileStatic
class UhlenScriptSupport {
    static final String MODEL_ID_LIKE_QUERY_PATTERN = "MODEL170711%"
    static final User submitter = getSubmitterAccount()

    static final String adminUsername = System.getenv("ADMIN_USER")
    // the current session
    static final SessionHolder session = null
    static final String constraintBasedModel = "http://identifiers.org/mamo/MAMO_0000009"
    static final ModellingApproach modellingApproach = lookupModellingApproach()

    /*
     * Returns the User account owning the models to be updated.
     *
     * All models were submitted by the same account, and we guard this assumption with a runtime (fatal) exception.
     *
     * @return the User account that should be used to update these models.
     */
    @CompileDynamic
    private static User getSubmitterAccount() {
        // we deliberately call get() because we expect a single result; getting >1 results would be an error which
        // would be propagated upstream to the callees of this method.
        User owner = Revision.createCriteria().get {
            projections {
                distinct "owner"
            }
            model {
                like "submissionId", MODEL_ID_LIKE_QUERY_PATTERN
            }
        } as User
        owner
    }

    @CompileDynamic
    private static ModellingApproach lookupModellingApproach() {
        ModellingApproach.findByResource(constraintBasedModel)
    }
}

/*
 * Model-centric log holder.
 *
 * Printing to System.out in a multi-threaded environment introduces unnecessary blocking and also
 * makes the order in which the statements are printed unpredictable.
 *
 * This class addresses both issues: all log messages pertaining to a particular model are queued, so
 * the order is preserved. Also, because we process each model in a dedicated thread, there's no need
 * to block.
 * See also the printModelLog() method.
 */
@CompileStatic
class ModelLogger {
    /**
     * Log for model-related messages.
     *
     * Keys represent model identifiers. Values represent pairs of ordered sets of messages
     * corresponding to the error log and the info log respectively.
     *
     * Since all messages relating to a model will be inserted by the same thread, there is no
     * need to use locks.
     */
    static ConcurrentHashMap<String, ModelLogger> messageLog = new ConcurrentHashMap<>()
    /**
     * The error log for this model
     */
    Set err
    /**
     * The message log for this model
     */
    Set out

    void logMsg(def msg) {
        out << msg
    }

    void errMsg(def msg) {
        err << msg
    }

    String toString() {
        "out: $out, err: $err"
    }
}

@CompileStatic
class FolderFilter implements FileFilter {
    public static final FolderFilter instance = new FolderFilter()

    boolean accept(File candidate) {
        candidate.isDirectory()
    }
}

@CompileStatic
class UhlenModelUpdater {
    static final AtomicInteger processedCount = new AtomicInteger()
    static final AtomicInteger failureCount = new AtomicInteger()
    final String modelFolder = System.getenv("MODEL_FOLDER")
    ApplicationContext ctx
    GrailsApplication grailsApp
    // auth token for admin account; used by worker threads to publish models
    Authentication submitterAuth
    Authentication adminAuth
    CamelContext camelContext

    void init() {
        submitterAuth = createTokenForUser(UhlenScriptSupport.submitter)
        adminAuth = createTokenForUser(UhlenScriptSupport.adminUsername)

        // set the application context reference in POGOs that expect it
        RevisionTransportCommand.context = ctx

        // don't let Camel shut itself down within 5 minutes of the importer finishing.
        // wait for all models to be indexed instead.
        camelContext = ctx.getBean "camelContext", CamelContext
        camelContext.shutdownStrategy.setTimeout(Long.MAX_VALUE)
    }

    /*
     * Creates and returns an authentication token for the given user.
     * Note that the owner of the credentials is *not* authenticated until the token is put in the SecurityContext.
     * Also note that, by default, SecurityContexts are thread-local.
     *
     * @param username the username for the account whose credentials should be used to create the authentication token
     * @return the authentication token which, if placed in the security context of the current thread, would allow us
     *      to log in as the given user.
     * @see grails.plugin.springsecurity.SpringSecurityUtils.doWithAuth(String, Closure)
     */
    UsernamePasswordAuthenticationToken createTokenForUser(User u) {
        assert u
        assert ctx: "ApplicationContext not initialised yet"
        UserDetailsService userDetailsService = ctx.getBean("userDetailsService", UserDetailsService)
        UserDetails userDetails = userDetailsService.loadUserByUsername(u.username)
        // first constructor argument needs to be a UserDetails instance
        new UsernamePasswordAuthenticationToken(userDetails, u.password, userDetails.authorities)
    }

    /*
     * Creates and returns an authentication token for the given user.
     *
     * @param username the username for the account whose credentials should be used to create the authentication token
     * @return an authentication token for the given user
     * @see {@link UhlenScriptSupport#createTokenForUser(net.biomodels.jummp.plugins.security.User)}
     */
    @CompileDynamic
    UsernamePasswordAuthenticationToken createTokenForUser(String username) {
        assert username : "Username required but not defined"
        createTokenForUser(User.findByUsername(username))
    }

    static void addModelMsg(String model, def msg) {
        def logger = getOrCreateModelLogger model
        logger.logMsg msg
    }

    static void addModelError(String model, def msg) {
        failureCount.incrementAndGet()
        def logger = getOrCreateModelLogger model
        logger.errMsg msg
    }

    static ModelLogger getOrCreateModelLogger(String model) {
        ModelLogger.messageLog.putIfAbsent(model,
            new ModelLogger(err: new LinkedHashSet(), out: new LinkedHashSet()))
        ModelLogger.messageLog[model]
    }

    static void printModelLog() {
        ModelLogger.messageLog.keySet().sort().each { String modelId ->
            ModelLogger logger = ModelLogger.messageLog[modelId]
            Set infoMessages = logger.out
            for (m in infoMessages) println("$modelId: $m")
        }
        if (failureCount.get() > 0) {
            println("Failed to import the following models:")
            ModelLogger.messageLog.keySet().sort().each { String modelId ->
                ModelLogger logger = ModelLogger.messageLog[modelId]
                Set errorMessages = logger.err
                for (m in errorMessages) System.err.println("$modelId: $m")
            }
        }
    }

    SessionHolder getCurrentSession() {
        SessionFactory factory = ctx.getBean "sessionFactory", SessionFactory
        TransactionSynchronizationManager.getResource(factory) as SessionHolder
    }

    static boolean markSessionAsRollbackOnly(SessionHolder session) {
        assert session: "Hibernate Session not available. Was persistenceInterceptor.init() called?"
        session.setRollbackOnly()
        session.isRollbackOnly()
    }

    /**
     * Returns the file system location where a given model's files are stored.
     *
     * @param model the model for which to look up the corresponding working directory subfolder.
     * @return a{@link File} denoting the model folder
     */
    File findModelDotGitDirectory(Model model) {
        assert model?.vcsIdentifier: "Model instance having a vcsIdentifier expected"
        assert grailsApp: "Missing grailsApplication bean reference 'grailsApp'. Are you using grails run-script ?"
        def base = grailsApp.config.flatten().get "jummp.vcs.workingDirectory"
        assert base instanceof String
        Paths.get(base, model.vcsIdentifier, ".git").toFile()
    }

    private static String performGitRevert(Repository repository, String ref) throws GitAPIException {
         ObjectId toRevert = Objects.requireNonNull(repository, "Model folder Git repo required")
            .resolve(ref)
        Git git = new Git(repository)
        def newHead = git.revert()
            .include(toRevert)
            .call()
        /* use git.reset().setMode(org.eclipse.jgit.api.ResetCommand.ResetType.HARD)
            .setRef("HEAD^").call() to undo if needed */

       newHead.name
    }

    /*
     * Handles the mechanics of reverting a model revision from the Git repo.
     *
     * You should probably call {@link revertGitRevision(Revision)} instead.
     * @param repository the initialised repository reference for that revision's model.
     * @param revision the revision whose file system changes we should revert
     * @throws GitAPIException if there was an internal error which prevented us from reverting the revision
     * @see {@link revertGitRevision()}
     */
    static void doRevertGitRevision(Repository repository, Revision revision) throws GitAPIException {
        String revisionId = Objects.requireNonNull(revision, "Revision to revert required").vcsId
        String newHead = performGitRevert repository, revisionId
        String msg = "Reverted ${revisionId}. HEAD is now $newHead"
        addModelMsg(revision.model.submissionId, msg)
    }

    private Object withGitRepoForRevision(Revision revision, Closure c) {
        assert revision
        Model model = revision.model
        File baseDir = findModelDotGitDirectory(model)

        Repository repository = GitSupport.buildRepository(baseDir)
        try {
            c.call(repository)
        } finally {
            repository.close()
        }
    }

    /**
     * Convenience method for reverting a revision in a Git repository.
     *
     * @param revision the revision whose file changes should be reverted.
     * @throws GitAPIException if JGit encountered an error while performing the revert command.
     */
    void revertGitRevision(Revision revision) throws GitAPIException {
        withGitRepoForRevision(revision) { Repository repository ->
            doRevertGitRevision(repository, revision)
        }
    }

    /**
     * Atomically deletes a revision, its repository files and associated ACL permissions.
     *
     * <p>Since {@link net.biomodels.jummp.core.ModelService#addValidatedRevision(java.util.List, java.util.List, net.biomodels.jummp.core.model.RevisionTransportCommand)}
     * inserts the new revision in a dedicated transaction which gets committed and flushed before the method returns, we
     * cannot use transaction rollback to undo that insertion &ndash; we need to use another dedicated transaction which
     * undoes that work.</p>
     * <p>We also run <tt>git revert</tt> so that the
     *
     * <p>This method will throw an {@code IllegalStateException} if any of the entities could not be deleted.</p>
     * @param toDelete the revision that should be deleted
     * @see UhlenModelUpdater#rollBackSessionAndRevision(net.biomodels.jummp.model.Revision, org.springframework.orm.hibernate4.SessionHolder)
     */
    void undoRevisionInsertion(Revision toDelete) {
        assert toDelete
        long rId = toDelete.id
        AclUtilService aclUtilService = ctx.getBean "aclUtilService", AclUtilService
        // a revision and its ACLs are inserted in a dedicated transaction, so we cannot simply
        def txSettings = [propagationBehavior: TransactionDefinition.PROPAGATION_NESTED,
                          isolationLevel     : TransactionDefinition.ISOLATION_READ_COMMITTED]
        Revision.withTransaction(txSettings) { TransactionStatus status ->
            try {
                aclUtilService.deleteAcl(toDelete)
                String query = "delete RepositoryFile rf where rf.revision = :revision"

                RepositoryFile.executeUpdate(query, [revision: toDelete])
                toDelete.delete(flush: true)
            } catch (Exception e) {
                // rollback everything in this transaction and notify the callee
                status.setRollbackOnly()
                String msg = "Could not delete Revision $rId: ${e.message}"
                throw new IllegalStateException(msg)
            }
            try {
                // database rollback ok, now try the reverting VCS changes for this revision
                revertGitRevision(toDelete)
            } catch (Exception e) {
                // VCS rollback failed, don't commit the database rollback to preserve consistency
                status.setRollbackOnly()
                String msg = "Could not revert VCS changes introduced by Revision $rId: $e"
                throw new IllegalStateException(msg, e)
            }
        }
    }

    /**
     * Marks the current Hibernate session as rollback only and atomically deletes all entities associated with a revision.
     *
     * <p>To be used as the preferred rollback mechanism in code invoked after the new model revision has been created and
     * persisted into the database via {@code modelService.addValidatedRevision( )}, assuming the insertion has been successful.</p>
     *
     * @param revision the revision which should be deleted
     * @see UhlenModelUpdater#undoRevisionInsertion(net.biomodels.jummp.model.Revision)
     * @see UhlenModelUpdater#markSessionAsRollbackOnly(org.springframework.orm.hibernate4.SessionHolder)
     */
    void rollBackSessionAndRevision(Revision revision, SessionHolder session) {
        markSessionAsRollbackOnly(session)
        undoRevisionInsertion(revision)
    }

    /**
     * Convenience method for performing operations within a Hibernate Session.
     * @param callback a closure defining the work to be done
     * @param submissionFolder the model folder on which to operate
     * @return the result of the work performed, possibly null.
     */
    Object doInSession(Closure callback) {
        // set up a Hibernate session
        PersistenceContextInterceptor persistenceInterceptor = ctx.getBean "persistenceInterceptor", PersistenceContextInterceptor
        SessionHolder session = null
        try {
            persistenceInterceptor?.init()
            session = getCurrentSession()
            callback.call(session)
        } finally {
            if (!session?.rollbackOnly) {
                persistenceInterceptor?.flush()
            }
            persistenceInterceptor?.destroy()
        }
    }

    Revision doInsertNewRevision(String modelId, File modelFolder, Model model) {
        Map<String, Object> revisionData = createRevisionCmdForModelFolder(modelId, modelFolder, model)
        if (!revisionData) { // something went wrong, the error has already been logged
            return null
        }
        RevisionTransportCommand revisionCmd = revisionData.revision as RevisionTransportCommand
        List<RepositoryFileTransportCommand> filesToAdd = revisionData.toAdd as List<RepositoryFileTransportCommand>
        List<RepositoryFileTransportCommand> filesToDelete = revisionData.toDelete as List<RepositoryFileTransportCommand>
        Revision newRevision = null
        ModelService modelService = ctx.getBean "modelService", ModelService
        try {
            modelService.addModellingApproachAsAnnotation(revisionCmd, UhlenScriptSupport.modellingApproach)
            addModelMsg(modelId, "Assigned modelling approach")
            newRevision = modelService.addValidatedRevision(filesToAdd, filesToDelete, revisionCmd)
        } catch (ModelException e) {
            assert markSessionAsRollbackOnly(getCurrentSession()): "Adding revision ${revisionCmd.properties} failed but could not roll back"
            addModelError(modelId, "ModelException thrown when inserting the new revision: $e.message")
        }
        newRevision
    }

    static RepositoryFileTransportCommand createRepoFile(File file, boolean isMainFile, String description) {
        new RepositoryFileTransportCommand(path: file.absolutePath, mainFile: isMainFile,
            userSubmitted: true, hidden: false, description: description)
    }

    /*
     * Infers the category for a submission given its files.
     *
     * All 21 updated Uhlen models have a predefined category they fall under.
     */
    @CompileDynamic
    static String lookupAutoGeneratedCategory(String modelId) {
        AutoGeneratedCategory category = AutoGeneratedCategory.findByModelIdentifier(modelId)
        assert category: "No category found for representative model $modelId"

        category.categoryName
    }

    @SuppressWarnings("GrMethodMayBeStatic")
    @CompileDynamic
    ModelFormat fetchModelFormat(ModelFormatTransportCommand cmd) {
        ModelFormat.findByIdentifierAndFormatVersion(cmd.identifier, cmd.formatVersion)
    }

    Map<String, Object> createRevisionCmdForModelFolder(String id, File folder, Model model) {
        def repoFileMap = createRepoFiles(folder)
        RepositoryFileTransportCommand modelFile = repoFileMap.main as RepositoryFileTransportCommand
        List<RepositoryFileTransportCommand> additionals = repoFileMap.additionals as List<RepositoryFileTransportCommand>
        def mainFiles = [new File(modelFile.path)]

        ModelFileFormatService modelFileFormatService = ctx.getBean "modelFileFormatService", ModelFileFormatService
        ModelFormatTransportCommand fmtCmd = modelFileFormatService.inferModelFormat([modelFile])
        ModelFormat fmt = fetchModelFormat(fmtCmd)
        List errors = []
        boolean isValid = modelFileFormatService.validate(mainFiles, fmt.identifier, errors)
        if (!isValid) {
            addModelError(id, "Model failed validation: $errors")
            return null
        }

        String modelName = modelFileFormatService.extractName(mainFiles, fmt)
        String modelDesc = modelFileFormatService.extractDescription(mainFiles, fmt)

        ModelTransportCommand modelCmd = new ModelTransportCommand(deleted: false, submissionId: model.submissionId)
        addModelMsg id, "fake mtc created"
        // avoid calling new ModelAdapter(model: model).toCommandObject(false) because, for
        // reasons not entirely understood yet, modelService.getSpringDatabaseRoles() returns an empty set
        // which causes the query in getLatestRevision() to throw a BadSqlGrammarException. This is because
        // we cannot use empty collections with the 'in' operator in HQL.
        //new ModelAdapter(model: model).toCommandObject(false)
        //addModelMsg id, "real mtc created"

        def repoFileCommands = [modelFile] + additionals
        def filesToDelete = getRepoFilesOfLastRevision(model)
        def revisionCmd = new RevisionTransportCommand(files: repoFileCommands, format: fmtCmd, validated: isValid,
            name: modelName, description: modelDesc, validationLevel: ValidationState.APPROVED,
            curationState: CurationState.NON_CURATED, minorRevision: false,
            comment: "Import of '$modelName'.", model: modelCmd)

        [revision: revisionCmd, toAdd: repoFileCommands, toDelete: filesToDelete]
    }

    static Map<String, Object> createRepoFiles(File folder) {
        def partitionedFiles = partitionMainAndAdditionalFiles(folder)
        File modelFile = partitionedFiles.main as File
        List<File> additionals = partitionedFiles.additionals as List<File>
        final String modelId = folder.name
        assert modelFile: "No main file found in submission folder $modelId"

        String modelCategory = lookupAutoGeneratedCategory(modelId)
        def mainFileRFTC = createRepoFile(modelFile, true, "Patient derived genome scale metabolic model for $modelCategory")
        def otherRepoFiles = additionals.collect { f ->
            createRepoFile f, false, "All '$modelCategory' models"
        }

        [main: mainFileRFTC, additionals: otherRepoFiles]
    }

    static Map<String, Object> partitionMainAndAdditionalFiles(File folder) {
        File modelFile = null
        // the main file is the SBML (.xml extension)
        // additionals should only contain <category_name>.zip -- the OMEX with the missing models
        List<File> additionals = []
        for (File child : folder.listFiles()) {
            if (child.name.endsWith('.xml')) {
                modelFile = child
            } else {
                additionals << child
            }
        }
        [main: modelFile, additionals: additionals]
    }

    List<RepositoryFileTransportCommand> getRepoFilesOfLastRevision(Model model) {
        Revision latest = model.revisions.max { it.revisionNumber }
        RepositoryFileService service = ctx.getBean("repositoryFileService", RepositoryFileService)
        service.getRepositoryFilesForRevision latest
    }

    /**
     * Makes a given revision readable to anyone.
     */
    void publish(Revision r) {
        SpringSecurityUtils.doWithAuth(UhlenScriptSupport.submitter.username) {
            AclUtilService aclUtilService = ctx.getBean "aclUtilService", AclUtilService
            aclUtilService.addPermission(r, "ROLE_USER", BasePermission.READ)
            aclUtilService.addPermission(r, "ROLE_ANONYMOUS", BasePermission.READ)
            r.state = ModelState.PUBLISHED
            if (!r.save()) {
                def err = r.errors.allErrors
                assert markSessionAsRollbackOnly(getCurrentSession()): "Publishing $r failed ($err), but we could not roll back the session"
                throw new IllegalStateException("Cannot publish revision ${r.id}: $err")
            }
        }
    }

    @CompileDynamic
    static Model findModelBySubmissionId(String id) {
        Model.findBySubmissionId(id)
    }

    /*
     * Support method for handleModelFolder()
     */
    void doHandleModelFolder(SessionHolder session, File submissionFolder) {
        assert submissionFolder?.isDirectory(): "'$submissionFolder' is not a model folder that exists"
        processedCount.incrementAndGet()
        String id = submissionFolder.name
        Model m = findModelBySubmissionId(id)
        assert m: "Model '$id' should have already been imported but isn't."

        Revision newRevision = doInsertNewRevision(id, submissionFolder, m)
        addModelMsg id, "inserted revision $newRevision"
        if (!newRevision || newRevision?.hasErrors()) {
            addModelError(id, "Model update failed: ${newRevision?.errors?.allErrors}")
            assert markSessionAsRollbackOnly(session): "No new revision could be inserted and we failed to roll back the current session"
        } else {
            Revision.withTransaction { status ->
                try {
                    // the session of this transaction is empty; attach the new revision to it
                    newRevision = Revision.get(newRevision.id)
                    publish newRevision
                    int deleteCount = markNonRepresentativeModelsAsDeleted(id)
                    addModelMsg(id, "Archived $deleteCount non-representative models.")
                } catch (JummpException e) {
                    addModelError(id, e.message)
                    rollBackSessionAndRevision newRevision, session
                }
            }
        }
    }

    /**
     * Updates the model, adds the modelling approach, publishes its latest version and
     * deletes the non-representative models for the model's category.
     */
    void handleModelFolder(File modelFolder) {
        doInSession { SessionHolder s ->
            doHandleModelFolder(s, modelFolder)
        }
    }

    @CompileDynamic
    static UhlenModelMapping findUhlenModelMapping(String submissionId) {
        UhlenModelMapping.findByRepresentative(submissionId)
    }

    /**
     * Archive non-representative models belonging to this category.
     *
     * <p>In order to avoid including non-representative models in the search results, we
     * need to mark them as deleted. The records are not actually removed, we simply set the
     * <tt>deleted</tt> column to <tt>true</tt> for the models in question.</p>
     *
     * <p>An assertion failure exception will be thrown if the model is not representative
     * for a Uhlen category or if the model does not exist in the database</p>
     * @param representativeId the submission id of a representative model for which we
     *          should delete the siblings.
     * @return the number of models that have been marked as deleted.
     */
    static int markNonRepresentativeModelsAsDeleted(String representativeId) {
        assert findUhlenModelMapping(representativeId): "'$representativeId' is not representative for a Uhlen2017 category"
        assert findModelBySubmissionId(representativeId): "No model with identifier '$representativeId' submitted"

        String query = """\
update Model m set m.deleted = true where m.submissionId in (
    select umm.member from UhlenModelMapping umm where umm.representative = :representative)"""
        Model.executeUpdate(query, [representative: representativeId])
    }

    void updateModels() {
        init()

        def duration
        def startTime = Instant.now()
        try {
            def modelFolderPattern = ~/^MODEL170711\d{4}$/

            File base = new File(modelFolder)
            processSubmissionsFolder(base, modelFolderPattern)
            awaitCompletionOfIndexingJobs()
        } catch (Exception e) {
            System.err.println("Generic exception encountered while importing the models: $e")
        } finally {
            duration = Duration.between(startTime, Instant.now())
            String formattedDuration = duration.toString()
            println("Imported ${processedCount.get()} models (${failureCount.get()} failures) in $formattedDuration")
            printModelLog()
        }
    }

    private void awaitCompletionOfIndexingJobs() {
        // wait for pending indexing jobs to complete before stopping
        def indexRequestDispatcher = camelContext.routes.find {
            // we use seda:exec to invoke the indexer
            it.consumer.endpoint.endpointKey.startsWith("seda://exec")
        }.consumer as SedaConsumer

        int pendingIndexingJobs = indexRequestDispatcher.pendingExchangesSize
        while (pendingIndexingJobs > 0) {
            println("Waiting for ${pendingIndexingJobs} models to be indexed...")
            Thread.sleep(30000)
            pendingIndexingJobs = indexRequestDispatcher.pendingExchangesSize
        }
    }

    private void submissionDetected(File root) {
        final String rootName = root.name
        SpringSecurityUtils.doWithAuth(UhlenScriptSupport.submitter.username) {
            try {
                handleModelFolder root
                println "handled $rootName"
            } catch (IllegalStateException ise) {
                addModelError(rootName, ise.message)
            } catch (AssertionError e) {
                addModelError rootName, e.toString()
            } catch (Exception e) {
                addModelError(rootName, "oops: $rootName -- $e")
                e.printStackTrace()
            }
        }
    }

    @CompileDynamic
    private void processSubmissionsFolder(File root, Pattern modelFolderPattern) {
        final int POOL_SIZE = Math.min(7, 2 * Runtime.getRuntime().availableProcessors())
        println("Pool size is $POOL_SIZE, model folder is $modelFolder")
        GParsPool.withPool(POOL_SIZE) {
            GParsPool.runForkJoin(root) { File dir ->
                final String dirName = dir.name
                if (dirName ==~ modelFolderPattern) {
                    submissionDetected dir
                } else { // fork dedicated task for each sub-folder
                    //descendIntoSubFolders(root)
                    def subFolders = dir.listFiles(FolderFilter.instance)
                    for (File child in subFolders) {
                        forkOffChild child
                    }
                }
            }
        }
    }
}

def updater = new UhlenModelUpdater(ctx: ctx, grailsApp: grailsApplication)
updater.updateModels()
