<div class="row">
    <div class="large-4 medium-4 small-12 columns">
        <a href="${createLink(controller: "search", action: "search", params:
            [query: "*:*&domain=biomodels"])}"
           title="Browse all literature models">
            <span class="size-400 icon icon-common icon-resource icon-spacer hide-for-small-only"></span></a>
        <h4><a href="${createLink(controller: "search", action: "search", params: [query: "*:*&domain=biomodels"])}"
               title="Browse all literature models">Individual models</a></h4>
        <h5>${totalIndividualModels} models</h5>
    </div>
    <div class="large-4 medium-4 small-12 columns">
        <a href="${createLink(controller: "search", action: "search", params:
            [query: "*:*&domain=biomodels_autogen"])}"
           title="Browse all auto generated models">
            <span class="size-400 icon icon-common icon-clone icon-spacer hide-for-small-only"></span></a>
        <h4><a href="${createLink(controller: "search", action: "search", params:
            [query: "*:*&domain=biomodels_autogen"])}"
               title="Browse all auto generated models">Auto gen</a></h4>
        <h5>${totalAutoGeneratedModels} models</h5>
    </div>
    <div class="large-4 medium-4 small-12 columns">
        <a href="${createLink(controller: "goChart", action: "index")}"
           title="Browse all literature models using GO chart">
            <span class="size-400 icon icon-conceptual icon-ontology icon-spacer hide-for-small-only"></span></a>
        <h4><a href="${createLink(controller: "goChart", action: "index")}"
               title="Browse all literature models using GO chart">GO Chart</a></h4>
        <h5>${totalGOClasses} GO classes</h5>
    </div>
</div>
