<div class="row">
    <div class="large-3 medium-3 small-12 columns">
        <g:link controller="search" action="search"
                params="${[query: '*:* AND curationstatus:"Manually curated"', domain: "biomodels"]}"
                title="Browse all manually curated models">
            <span class="size-400 icon icon-common icon-reviewed-data hide-for-small-only"></span></g:link>
        <h4><g:link controller="search" action="search"
                    params="${[query: '*:* AND curationstatus:"Manually curated"', domain: "biomodels"]}"
                    title="Browse all manually curated models">Manually Curated</g:link></h4>
        <h5 class="show-for-small-only">${totalCuratedModels} models</h5>
    </div>
    <div class="large-3 medium-3 small-12 columns">
        <g:link controller="search" action="search"
                params="${[query: '*:* AND curationstatus:"Non-curated"', domain: "biomodels"]}"
                title="Browse all non-curated models">
            <span class="size-400 icon icon-common icon-unreviewed-data hide-for-small-only"></span></g:link>
        <h4><g:link controller="search" action="search"
                    params="${[query: '*:* AND curationstatus:"Non-curated"', domain: "biomodels"]}"
                    title="Browse all non-curated models">Non-curated</g:link></h4>
        <h5 class="show-for-small-only">${totalNonCuratedModels} models</h5>
    </div>
    <div class="large-3 medium-3 small-12 columns">
        <g:link controller="search" action="search"
                params="${[query: "*:*", domain: "biomodels_autogen"]}"
                title="Browse all auto generated models">
            <span class="size-400 icon icon-common icon-clone icon-spacer hide-for-small-only"></span></g:link>
        <h4><g:link controller="search" action="search"
                    params="${[query: "*:*", domain: "biomodels_autogen"]}"
                    title="Browse all auto generated models">Auto generated</g:link></h4>
        <h5 class="show-for-small-only">${totalAutoGeneratedModels} models</h5>
    </div>
    <div class="large-3 medium-3 small-12 columns">
        <a href="${createLink(controller: "goChart", action: "index")}"
           title="Browse all literature models using GO chart">
            <span class="size-400 icon icon-conceptual icon-ontology icon-spacer hide-for-small-only"></span></a>
        <h4><a href="${createLink(controller: "goChart", action: "index")}"
               title="Browse all literature models using GO chart">GO Chart</a></h4>
        <h5 class="show-for-small-only">${totalGOClasses} classes</h5>
    </div>
</div>
<div class="row hide-for-small-only">
    <div class="large-3 medium-3 small-12 columns">
        <h5>${totalCuratedModels} models</h5>
    </div>
    <div class="large-3 medium-3 small-12 columns">
        <h5>${totalNonCuratedModels} models</h5>
    </div>
    <div class="large-3 medium-3 small-12 columns">
        <h5>${totalAutoGeneratedModels} models</h5>
    </div>
    <div class="large-3 medium-3 small-12 columns">
        <h5>${totalGOClasses} classes</h5>
    </div>
</div>
